[project]
name = "sam"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "bcrypt==4.3.0",
    "certifi==2025.1.31",
    "cffi==1.17.1",
    "charset-normalizer==3.4.1",
    "cryptography==44.0.2",
    "idna==3.10",
    "mysql-connector-python>=9.0.0",
    "paramiko==3.5.1",
    "pycparser==2.22",
    "pynacl==1.5.0",
    "pyodbc==5.2.0",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.0.1",
    "pytz==2025.2",
    "requests==2.32.3",
    "requests-mock==1.12.1",
    "schedule==1.2.2",
    "six==1.17.0",
    "sshtunnel>=0.4.0",
    "urllib3==2.2.3",
    "waitress==3.0.0",
]
