openapi: 3.0.1
info:
  title: "SAM Callback Service API"
  description: |
    API para recibir y procesar notificaciones de callback desde Automation Anywhere A360.
  version: "2.2.0"
servers:
  - url: http://localhost:8008
    description: Servidor de desarrollo local.

paths:
  /:
    post:
      summary: "Recibir notificación de callback de A360"
      description: |
        Endpoint único que recibe una solicitud POST con un cuerpo JSON que contiene el estado final de una ejecución de bot (despliegue) en A360.
        La solicitud debe incluir un encabezado 'X-Authorization' para la autenticación.
      tags:
        - "Callback"
      security:
        - ApiKeyAuth: []
      requestBody:
        description: "Payload JSON enviado por A360 al finalizar una ejecución."
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CallbackPayload'
            examples:
              exito_con_output:
                summary: "Ejemplo de ejecución exitosa con output"
                value:
                  deploymentId: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
                  status: "COMPLETED"
                  botOutput: {"clave": "valor"}
              exito_sin_output:
                summary: "Ejemplo de ejecución exitosa sin output"
                value:
                  deploymentId: "b2c3d4e5-f6a7-8901-2345-67890abcdef1"
                  status: "COMPLETED"
      responses:
        '200':
          description: "Éxito. El callback fue recibido y procesado correctamente."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: "Solicitud Incorrecta. El servidor no puede procesar la solicitud debido a un error del cliente (p. ej., JSON malformado, campos inválidos o faltantes)."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                example:
                  status: "SOLICITUD_INVALIDA"
                  message: "El campo 'deploymentId' es requerido y no puede estar vacío."
        '401':
          description: "Autenticación Fallida. La solicitud carece de credenciales de autenticación válidas. Se requiere un token válido en el encabezado 'X-Authorization'."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                example:
                  status: "AUTENTICACION_FALLIDA"
                  message: "El token proporcionado en 'X-Authorization' es inválido o ha expirado."
        '405':
          description: "Método No Permitido. El método de solicitud (p. ej., GET, PUT) no está soportado para este endpoint."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                example:
                  status: "METODO_NO_PERMITIDO"
                  message: "El método de solicitud 'GET' no está soportado. Utilice 'POST'."
        '413':
          description: "Carga Útil Demasiado Grande. El tamaño de la solicitud excede el límite permitido por el servidor."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                example:
                  status: "PAYLOAD_MUY_GRANDE"
                  message: "El cuerpo de la solicitud excede el límite de tamaño máximo de 1MB."
        '500':
          description: "Error Interno del Servidor. El servidor encontró una condición inesperada que le impidió completar la solicitud. Contacte al administrador del sistema."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
                example:
                  status: "ERROR_INTERNO"
                  message: "Ocurrió un error inesperado en el servidor al procesar la solicitud."

components:
  schemas:
    CallbackPayload:
      title: "Payload del Callback"
      type: object
      required:
        - deploymentId
        - status
      properties:
        deploymentId:
          type: string
          description: "ID único del despliegue (ejecución del bot) en A360. Cadena no vacía."
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        status:
          type: string
          description: "Estado final de la ejecución del bot. Cadena no vacía."
          example: "COMPLETED"
        botOutput:
          type: object
          description: "(Opcional) Diccionario que contiene las variables de salida del bot. Si no se provee, se asume un objeto vacío."
          example: {"status": "OK", "download_path": "/share/file.xlsx"}
    
    SuccessResponse:
      title: "Respuesta Exitosa"
      type: object
      properties:
        status:
          type: string
          description: "Indica que la operación fue exitosa."
          example: "OK"
        message:
          type: string
          description: "Mensaje de confirmación."
          example: "Callback procesado y registrado exitosamente."

    ErrorResponse:
      title: "Respuesta de Error"
      type: object
      properties:
        status:
          type: string
          description: "Código interno legible que representa el tipo de error."
          example: "AUTENTICACION_FALLIDA"
        message:
          type: string
          description: "Mensaje legible por humanos que describe el error en detalle."
          example: "Credenciales de autorización no válidas o ausentes."

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Authorization
      description: "Token de seguridad para validar la autenticidad de la llamada desde A360."
