openapi: 3.0.0
info:
  title: SAM Callback Service API
  version: 2.3.0
  description: >
    API para recibir callbacks desde Control Room mediante el apigw. 
    Requiere token de autorización enviado en el header **X-Authorization**.
servers:
  - url: http://10.167.181.41:8008
    description: Servidor de Producción
  - url: http://10.167.181.42:8008
    description: Servidor de Desarrollo
paths:
  /api/callback:
    post:
      summary: "Recibir notificación de callback de A360"
      description: >
        Endpoint único que recibe una solicitud POST con un cuerpo JSON que contiene el estado de una ejecución de bot en A360.
        **La solicitud debe incluir un encabezado 'X-Authorization' válido para la autenticación.**.
      parameters:
        - in: header
          name: X-Authorization
          required: true
          description: Token de autorización para validar la petición.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - deploymentId
                - status
              properties:
                deploymentId:
                  type: string
                  description: Identificador único del deployment.
                status:
                  type: string
                  description: Estado de la ejecución (ej. FINISHED, ERROR).
                deviceId:
                  type: string
                  description: Identificador del dispositivo que ejecutó el bot.
                userId:
                  type: string
                  description: Identificador del usuario asociado a la ejecución.
                botOutput:
                  type: object
                  description: Salida generada por el bot.
      responses:
        '200':
          description: Callback procesado correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  message:
                    type: string
                    example: Callback procesado.
        '400':
          description: Petición inválida (JSON malformado o faltan campos requeridos).
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  message:
                    type: string
                    example: Cuerpo de la petición vacío o inválido.
        '401':
          description: Token de autorización inválido o ausente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  message:
                    type: string
                    example: Token de autorización inválido.
        '405':
          description: Método no permitido (solo se acepta POST).
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  message:
                    type: string
                    example: Método no permitido. Solo se acepta POST.
        '500':
          description: Error interno del servidor (por ejemplo, conexión a la BD no disponible).
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ERROR
                  message:
                    type: string
                    example: Error interno del servidor durante el procesamiento.
