openapi: 3.0.1
info:
  title: "SAM Callback Service API"
  version: "2.3.0"
  description: |
    API para recibir callbacks desde Control Room a través del API Gateway.
    **Requiere obligatoriamente un token de autorización en el header `X-Authorization`.**
servers:
  - url: "http://10.167.181.41:8008"
    description: Servidor de Producción
  - url: "http://10.167.181.42:8008"
    description: Servidor de Desarrollo

paths:
  /api/callback:
    post:
      summary: "Recibir notificación de callback de A360"
      description: |
        Endpoint único que recibe una solicitud POST con el estado final de una ejecución de bot en A360.
        La autenticación mediante el header `X-Authorization` es obligatoria.
      tags:
        - "Callback"
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CallbackPayload'
      responses:
        '200':
          description: "Callback procesado correctamente."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: "Petición inválida (JSON malformado o faltan campos requeridos)."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: "Autenticación Fallida. El token en 'X-Authorization' es inválido o no fue proporcionado."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: "Ruta no encontrada. El endpoint solicitado no existe."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '405':
          description: "Método no permitido (solo se acepta POST)."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: "Error interno del servidor."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CallbackPayload:
      type: object
      required:
        - deploymentId
        - status
      properties:
        deploymentId:
          type: string
          description: "Identificador único del deployment."
        status:
          type: string
          description: "Estado de la ejecución (ej. COMPLETED, FAILED)."
        deviceId:
          type: string
          description: "(Opcional) Identificador del dispositivo que ejecutó el bot."
        userId:
          type: string
          description: "(Opcional) Identificador del usuario asociado a la ejecución."
        botOutput:
          type: object
          description: "(Opcional) Salida generada por el bot."
          additionalProperties: true

    SuccessResponse:
      type: object
      properties:
        status:
          type: string
          example: "OK"
        message:
          type: string
          example: "Callback procesado."

    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: "ERROR"
        message:
          type: string
          example: "Token de autorización inválido."

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Authorization
      description: "Token de seguridad para validar que la llamada es legítima."
